// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCkz-Bc2HNL9wm55Rum0aR1ZmIGY-DWxk',
    appId: '1:809013068698:web:046d381ae6b1fc585e7023',
    messagingSenderId: '809013068698',
    projectId: 'chat-app-94828',
    authDomain: 'chat-app-94828.firebaseapp.com',
    storageBucket: 'chat-app-94828.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuWYTTOS7iHb7y_OnrtMI9a9MsY40xlcM',
    appId: '1:809013068698:android:548b0c8e67c1ba645e7023',
    messagingSenderId: '809013068698',
    projectId: 'chat-app-94828',
    storageBucket: 'chat-app-94828.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt7hlW_bR4tYVIHl1cVeXQytuxZtlQZHI',
    appId: '1:809013068698:ios:9373d371b7209b0a5e7023',
    messagingSenderId: '809013068698',
    projectId: 'chat-app-94828',
    storageBucket: 'chat-app-94828.firebasestorage.app',
    iosBundleId: 'com.example.messenger',
  );
}
